<?php

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions form
 */
function suggestions_theme_suggestions_form_alter(array &$suggestions, array &$variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $form_id = str_replace('-', '_', $variables['element']['#id']);
        $suggestions[] = $hook . '__' . $form_id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions field details
 */
function suggestions_theme_suggestions_details_alter(array &$suggestions, array &$variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $id = str_replace("-", "_", $variables['element']['#id']);
        $suggestions[] = $hook . '__' . $id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions field input
 */
function suggestions_theme_suggestions_input_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        //if (strpos($variables['element']['#id'], 'edit-field-exemple-') === 0) {
        // $suggestions[] = $hook .'__' .  $variables['element']['#type'].'__' . 'exemple';
        //}
        $id = str_replace("-", "_", $variables['element']['#id']);
        $suggestions[] = $hook . '__' . $id;
    }
}


/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions field table
 */
function suggestions_theme_suggestions_table_alter(array &$suggestions, array &$variables, $hook)
{
    if (isset($variables['attributes']['id'])) {
        $table_id = $variables['attributes']['id'];
        $id = str_replace("-", "_", $table_id);
        $suggestions[] = $hook . '__' . $id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions field file managed
 */
function suggestions_theme_suggestions_file_managed_file_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $id = str_replace("-", "_", $variables['element']['#id']);
        $suggestions[] = $hook . '__' . $id;
    }

}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions form element
 */
function suggestions_theme_suggestions_form_element_alter(array &$suggestions, array $variables, $hook)
{
    $elementId = str_replace('-', '_', $variables['element']['#id']);
    $suggestions[] = $hook . '__' . $elementId;
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions container
 */
function suggestions_theme_suggestions_container_alter(array &$suggestions, array $variables, $hook)
{
    $pieces = [
        $variables['element']['#type'],
    ];
    $suggestions[] = $hook . implode('_', $pieces);
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions form element label
 */
function suggestions_theme_suggestions_form_element_label_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $id = $variables['element']['#id'];
        $suggestions[] = $hook . '__' . $id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions fieldset
 */
function suggestions_theme_suggestions_fieldset_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $id = $variables['element']['#id'];
        $suggestions[] = $hook . '__' . $id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions checkboxes
 */
function suggestions_theme_suggestions_checkboxes_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $id = $variables['element']['#id'];
        $suggestions[] = $hook . '__' . $id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions pager
 */
function suggestions_theme_suggestions_pager_alter(array &$suggestions, array $variables, $hook)
{
    $current_path = \Drupal::service('path.current')->getPath();
    $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);

    $path_alias = trim($result, '/');
    $path_alias = str_replace('/', '-', $path_alias);
    $path_alias = str_replace('-', '_', $path_alias);

    $suggestions[] = $hook . '__' . $path_alias;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 * @param array $suggestions
 * @param array $variables
 */
function suggestions_theme_suggestions_block_alter(array &$suggestions, array $variables, $hook)
{
    $element = $variables['elements'];
    if (!empty($element['content']['#block_content'])) {
        $block_bundle = $element['content']['#block_content']->bundle();
        $suggestions[] = $hook . '__' . $block_bundle;
    }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function suggestions_theme_suggestions_views_exposed_form_alter(array &$suggestions, array $variables)
{
    $suggestions[] = 'views_exposed_form__' . str_replace(
            ['views-exposed-form-', '-'],
            ['', '_'],
            $variables['form']['#id']);
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions view
 */
function suggestions_theme_suggestions_views_view_alter(array &$suggestions, array &$variables, $hook)
{
    if ($variables['view']->id() && $variables['view']->current_display) {
        $suggestions[] = $hook . '__' . $variables['view']->id() . '__' . $variables['view']->current_display;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 * suggestions view unformatted
 */
function suggestions_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array &$variables, $hook)
{
    if ($variables['view']->id() && $variables['view']->current_display) {
        $suggestions[] = $hook . '__' . $variables['view']->id() . '__' . $variables['view']->current_display;
    }
}


/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function suggestions_theme_suggestions_radios_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $id = str_replace("-", "_", $variables['element']['#id']);
        $suggestions[] = $hook . '__' . $id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function suggestions_theme_suggestions_select_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['element']['#id'])) {
        $id = str_replace("-", "_", $variables['element']['#id']);
        $suggestions[] = $hook . '__' . $id;
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function suggestions_theme_suggestions_paragraph_alter(array &$suggestions, array &$variables, $hook)
{
    $paragraph = $variables['elements']['#paragraph'];
    $node = \Drupal::routeMatch()->getParameter('node');
    if (!empty($node)) {
        $suggestions[] = $hook . '__' . $paragraph->bundle() . '__' . $node->getType() . '__' . $node->id();
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function suggestions_theme_suggestions_page_alter(array &$suggestions, array &$variables, $hook)
{
    if ($node = \Drupal::request()->attributes->get('node')) {
        array_splice($suggestions, 1, 0, $hook . '__' . $node->getType());
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function suggestions_theme_suggestions_node_alter(array &$suggestions, array &$variables, $hook)
{
    if ($node = \Drupal::request()->attributes->get('node')) {
        array_splice($suggestions, 1, 0, $hook . '__' . $node->getType());
    }
}

/**
 * Implements hook_theme_suggestions_html_alter().
 */
function suggestions_theme_suggestions_html_alter(array &$suggestions, array $variables, $hook)
{
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $suggestions[] = $hook . '__' . $node->bundle();
    }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function suggestions_theme_suggestions_taxonomy_term_alter(&$suggestions, $variables)
{
    $elements = $variables['elements'];
    if (isset($elements['#taxonomy_term']) && isset($elements['#theme']) && isset($elements['#view_mode'])) {
        $term = $elements['#taxonomy_term'];

        if (is_object($term)) {
            $suggestions[] = $elements['#theme'] . '__' . $term->getVocabularyId() . '__' . $elements['#view_mode'];
            $suggestions[] = $elements['#theme'] . '__' . $term->id() . '__' . $elements['#view_mode'];
        }
    }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function suggestions_theme_suggestions_field_alter(&$suggestions, $variables, $hook)
{
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $suggestions[] = $hook . '__' . $node->id();
    }
}

/**
 * Implements hook_theme_suggestions_user_alter().
 */
function suggestions_theme_suggestions_user_alter(array &$suggestions, array $variables, $hook)
{
    if ($view_mode = $variables['elements']['#view_mode']) {
        $suggestions[] = $hook . '__' . $view_mode;
    }
}